spring:
  application:
    name: gateway
  profiles:
    include: route
  cloud:
    nacos:
      server-addr: 192.168.10.128:8848
      config:
        import-check:
          enabled: false
server:
  port: 80
