server:
  port: 8081
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 192.168.10.128:8848
      config:
        server-addr: 192.168.10.128:8848
  elasticsearch:
    uris: http://192.168.10.128:9200
    username: elastic
    password: qihuis
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml