server:
  port: 8080
  servlet:
    context-path: /consumer
logging:
  level:
    com.qihui.sun.service: debug
spring:
  application:
    name: consumer
  profiles:
    active: dev
    include: dataSource
  cloud:
    nacos:
      server-addr: 192.168.10.128:8848
      config:
        namespace: ${spring.profiles.active}
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 1000
            logger-level: full
          producer:
            connect-timeout: 1000
            read-timeout: 1000
feign:
  sentinel:
    enabled: true
---
spring:
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=consumer
      - optional:nacos:common.yml
    activate:
      on-profile: dev
