server:
  port: 8081
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: qihuis
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml