server:
  port: 8081
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 192.168.10.128:8848
      config:
        server-addr: 192.168.10.128:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml
  elasticsearch:
    uris: http://192.168.10.128:9200
    username: elastic
    password: qihuis
  kafka:
    bootstrap-servers: 192.168.10.128:9092
    consumer:
      group-id: consumer-group # 消费者组id
      auto-offset-reset: earliest # 当没有已提交的偏移量时，从什么位置开始消费，earliest：最早的偏移量；latest：最新的偏移量
      enable-auto-commit: false # 是否自动提交偏移量，默认为true
      auto-commit-interval: 1000 # 自动提交偏移量的间隔时间，默认为1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500 # 单次poll最大拉取的记录数，默认为500
    listener:
      ack-mode: manual_immediate # 手动提交偏移量
  data:
    redis:
      host: 192.168.10.128
      port: 6379
      password: qihuis
      lettuce:
        pool:
          max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          max-wait: 1000ms # 当连接池资源耗尽时，调用者的最大等待时间（默认为-1，表示无限等待）