server:
  port: 8080
spring:
  application:
    name: producer
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml