server:
  port: 8080
spring:
  application:
    name: producer
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 192.168.10.128:8848
      config:
        server-addr: 192.168.10.128:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml