server:
  port: 9000
  servlet:
    context-path: /producer
spring:
  application:
    name: producer
  profiles:
    active: dev
    include: dataSource
  cloud:
    nacos:
      server-addr: 192.168.10.128:8848
      config:
        namespace: ${spring.profiles.active}
        import-check:
          enabled: false
---
spring:
  config:
    import:
      - nacos:producer.yml?group=producer
      - nacos:common.yml
    activate:
      on-profile: dev
